### PR TITLE
Show a list of the user's Firebases (including auth tokens)

### PR DESCRIPTION
**Pull request by lukasklein**
I thought it would be nice to see a list of the user's existing Firebases under the url-input, so that you don't have to copy and paste everything every time you want to use vulcan.

Since this is the first time I have ever touched ReactJS and Chrome extensions, I fear my code is rather messy. I welcome any cleanups or additions :)

Ideas:
- [ ] make it pretty
- [ ] make the list clickable (and prepopulate the inputs; I might dive deeper into React in the next days)
- [ ] check if user is logged in on firebase.com

comparing_firebase_master___lukasklein_master_ _lukasklein_vulcan

### CODE REVIEW

**Comment by 1j01** [comment]
Suggestion: move the token input back up with the URL input so that URLs and tokens are always together. :link: :revolving_hearts: :key:

**Comment by joeyyang** [comment]
@lukasklein – thank you for the PR! I'm a UX Engineer at Firebase, and I'd love to take a further look here. Would you mind adding me as a collaborator as well? Thanks!

**Comment by lukasklein** [comment]
@joeyyang Sure, I've added you. Thanks!

**Comment by joeyyang** [comment]
@lukasklein thanks so much for this Lukas — it was the inspiration for some much needed TLC. The new version now has email / PW login — [check it out](https://chrome.google.com/webstore/detail/vulcan-by-firebase/oippbnlmebalopjbkemajgfbglcjhnbl) and let me know what you think!

**Pull request closed without merging**
